
jobs:
- job: osx
  pool:
    vmImage: macOS-10.14
  timeoutInMinutes: 360
  variables:
    CONFIG: osx_arm64_python3.8.____cpython
    R_CONFIG: 
    ARROW_VERSION: 4.0.0
    UPLOAD_PACKAGES: False
  steps:
  - script: |
      echo "Removing homebrew from Azure to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew
    displayName: Remove homebrew

  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      sudo chown -R $USER $CONDA
    displayName: Add conda to PATH

  - script: |
      source activate base
      conda install -n base -c conda-forge --quiet --yes conda-forge-ci-setup=3 conda-build
    displayName: 'Add conda-forge-ci-setup=3'

  - script: |
      git clone --no-checkout https://github.com/kszucs/arrow arrow
      git -C arrow fetch -t https://github.com/kszucs/arrow release-4.0.0-rc0
      git -C arrow checkout FETCH_HEAD
      git -C arrow submodule update --init --recursive
    displayName: Clone arrow


  - script: |
      source activate base
      echo "Configuring conda."

      setup_conda_rc ./ ./ ./.ci_support/${CONFIG}.yaml
      export CI=azure
      source run_conda_forge_build_setup
      conda update --yes --quiet --override-channels -c conda-forge -c defaults --all
    displayName: Configure conda and conda-build
    workingDirectory: arrow/dev/tasks/conda-recipes
    env:
      OSX_FORCE_SDK_DOWNLOAD: "1"

  - script: |
      source activate base
      mangle_compiler ./ ./ ./.ci_support/${CONFIG}.yaml
    workingDirectory: arrow/dev/tasks/conda-recipes
    displayName: Mangle compiler

  - script: |
      source activate base
      make_build_number ./ ./ ./.ci_support/${CONFIG}.yaml
    workingDirectory: arrow/dev/tasks/conda-recipes
    displayName: Generate build number clobber file

  - script: |
      source activate base
      set +x
      if [[ "${CONFIG}" == osx_arm* ]]; then
        EXTRA_CB_OPTIONS="${EXTRA_CB_OPTIONS:-} --no-test"
      fi
      conda build arrow-cpp \
        -m ./.ci_support/${CONFIG}.yaml \
        --clobber-file ./.ci_support/clobber_${CONFIG}.yaml \
        ${EXTRA_CB_OPTIONS:-} \
        --output-folder ./build_artifacts

      if [ ! -z "${R_CONFIG}" ]; then
        conda build r-arrow \
          -m ./.ci_support/r/${R_CONFIG}.yaml \
          --output-folder ./build_artifacts
      fi
    workingDirectory: arrow/dev/tasks/conda-recipes
    displayName: Build recipes

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
  - script: pip install -e arrow/dev/archery[crossbow]
    displayName: Install Crossbow
  - bash: |
      archery crossbow \
        --queue-path $(pwd) \
        --queue-remote https://github.com/ursacomputing/crossbow.git \
        upload-artifacts \
        --sha release-4.0.0-rc0-0-azure-conda-osx-arm64-clang-py38 \
        --tag release-4.0.0-rc0-0-azure-conda-osx-arm64-clang-py38 \
        --pattern "arrow/dev/tasks/conda-recipes/build_artifacts/osx-*/*.tar.bz2"
    env:
      CROSSBOW_GITHUB_TOKEN: $(CROSSBOW_GITHUB_TOKEN)
    displayName: Upload packages as a GitHub release

  